# Change these first
owner: mbaharip # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Website
    url: https://www.mbaharip.me
    maxResponseTime: 5000
  - name: API Endpoint
    url: https://api.mbaharip.me/server
    maxResponseTime: 5000
  - name: CDN Server
    url: https://cdn.mbaharip.me
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mbaharip.me
#   baseUrl: /upptime
  logoUrl: https://cdn.mbaharip.me/api?path=/favicon.svg&raw=true
  faviconSvg: https://cdn.mbaharip.me/api?path=/favicon.svg&raw=true
  name: mbahArip Status
  theme: night
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
